name: build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]
        cc: [""]
        include:
        - os: ubuntu-20.04
          cc: CC=/usr/bin/gcc-10 CXX=/usr/bin/g++-10
          setup: |
            sudo apt-get update
            sudo apt-get install -y gcc-10 g++-10
    steps:
    - uses: actions/checkout@v2
    - name: setup
      if: ${{ matrix.setup }}
      run: ${{ matrix.setup }}
    - name: install dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get install -y swig3.0 uthash-dev tcl-dev check
    - name: install dependendencies on macOS
      if: runner.os == 'macOs'
      run: brew install autoconf automake libtool pkg-config swig php check
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ${{ matrix.cc }} ./configure
    - name: make
      run: make
    - name: check
      run: make check

  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make dist
      run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: source-dist
        path: owfs-*.*p*.tar.gz

  build-from-dist:
    needs: dist
    runs-on: ubuntu-latest
    steps:
    # FIXME: reusing steps from job build.
    # Verify if this is possible without copying verbatim.
    # Natural solution would be YAML anchors and pointers, but these
    # are not supported yet.
    - name: install dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get install -y swig3.0 uthash-dev tcl-dev check
    - uses: actions/download-artifact@v2
      with:
        name: source-dist
    - name: extract sources
      run: tar -x -f owfs-*.tar.gz --strip-components 1
    - name: configure
      run: ./configure
    - name: make
      run: make
